### ISSUE TITLE
Update branch file by Miaad  

### ISSUE THREAD

**Issue by QAIS-ALOMRANI** [QAIS-ALOMRANI/QAIS_19F19720#1]
Create a data type (int) for variable i @Miaad2000

**Comment by Miaad2000** [comment]
int subj_1,subj_2,subj_3,subj_4,subj_5
for (int i=1; i<=100; i++)
read subj_1,subj_2,subj_3,subj_4,subj_5
sum_average = subj_1+subj_2+subj_3+subj_4+subj_5 / 5
print sum_average

**Comment by QAIS-ALOMRANI** [comment]
Miaad is completed
